artifactId=template
parentArtifactId=ProjectTemplate
ProjectName=Template
package=com.youneng.troy
archetype.groupId=com.youneng.troy
archetype.artifactId=archetype-rich
archetype.version=1.0.1-SNAPSHOT
excludePatterns=**/.idea/**,**/*.iml,**/*.sh
