<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>ProjectTemplate</artifactId>
    <groupId>com.youneng.troy</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>template-dao</artifactId>
  <version>${dao-version}</version>

  <dependencies>
    <!-- 依赖项目自身的包,请勿增删 start -->
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-common</artifactId>
    </dependency>
    <!-- 依赖项目自身的包,请勿增删 end -->

    <!--troy自定义组件依赖 start -->
    <dependency>
      <groupId>com.youneng.seal</groupId>
      <artifactId>seal-mybatis-plugins</artifactId>
    </dependency>
    <dependency>
      <groupId>com.youneng.seal</groupId>
      <artifactId>seal-mybatis-plugins</artifactId>
    </dependency>
    <dependency>
      <groupId>com.xdf.pscommon</groupId>
      <artifactId>base-dynamic-datasource</artifactId>
    </dependency>
    <!--troy自定义组件依赖 end -->

    <!-- Spring相关 -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid-spring-boot-starter</artifactId>
    </dependency>

    <!-- 第三方 -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.pagehelper</groupId>
      <artifactId>pagehelper-spring-boot-starter</artifactId>
    </dependency>
  </dependencies>
</project>
