<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>ProjectTemplate</artifactId>
    <groupId>com.youneng.troy</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>template-web</artifactId>
  <version>${web-version}</version>

  <dependencies>

    <!--项目自身的包依赖 -->
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-biz</artifactId>
    </dependency>
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-service</artifactId>
    </dependency>

    <!-- 框架依赖 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-context</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-openfeign-core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-tx</artifactId>
    </dependency>


    <!-- troy自定义组件依赖 -->
    <dependency>
      <groupId>com.xdf.pscommon.alert</groupId>
      <artifactId>base-alert-starter</artifactId>
    </dependency>

    <!-- 其他三方框架依赖 -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>transmittable-thread-local</artifactId>
    </dependency>

  </dependencies>

  <build>
    <finalName>tiger-web</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <mainClass>com.youneng.tiger.web.TigerApplication</mainClass>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>


</project>
