<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <parent>
    <artifactId>ProjectTemplate</artifactId>
    <groupId>com.youneng.troy</groupId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>template-service</artifactId>
  <version>${service-version}</version>


  <dependencies>
    <!-- 依赖项目自身的包,请勿增删 start -->
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-dao</artifactId>
    </dependency>
    <dependency>
      <groupId>com.youneng.troy</groupId>
      <artifactId>template-common</artifactId>
    </dependency>
    <!-- 依赖项目自身的包,请勿增删 end -->

    <!-- spring框架依赖 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-context</artifactId>
    </dependency>

    <!-- troy自定义组件依赖 -->
    <dependency>
      <groupId>com.xdf.pscommon.alert</groupId>
      <artifactId>base-alert-starter</artifactId>
    </dependency>
  </dependencies>

</project>
